# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator_left
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_kinova_arm_joint_1
    - left_kinova_arm_joint_2
    - left_kinova_arm_joint_3
    - left_kinova_arm_joint_4
    - left_kinova_arm_joint_5
    - left_kinova_arm_joint_6
    - left_kinova_arm_joint_7
    - right_kinova_arm_joint_1
    - right_kinova_arm_joint_2
    - right_kinova_arm_joint_3
    - right_kinova_arm_joint_4
    - right_kinova_arm_joint_5
    - right_kinova_arm_joint_6
    - right_kinova_arm_joint_7
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_kinova_arm/left_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_kinova_arm_joint_1
      - left_kinova_arm_joint_2
      - left_kinova_arm_joint_3
      - left_kinova_arm_joint_4
      - left_kinova_arm_joint_5
      - left_kinova_arm_joint_6
      - left_kinova_arm_joint_7
  - name: right_kinova_arm/right_kinova_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_kinova_arm_joint_1
      - right_kinova_arm_joint_2
      - right_kinova_arm_joint_3
      - right_kinova_arm_joint_4
      - right_kinova_arm_joint_5
      - right_kinova_arm_joint_6
      - right_kinova_arm_joint_7
