controller_list:
  - name: fake_manipulator_controller
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
initial:  # Define initial robot poses.
  - group: manipulator
    pose: vertical