controller_list:
  - name: /left_ur/left_ur_arm_scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_ur_arm_shoulder_pan_joint
      - left_ur_arm_shoulder_lift_joint
      - left_ur_arm_elbow_joint
      - left_ur_arm_wrist_1_joint
      - left_ur_arm_wrist_2_joint
      - left_ur_arm_wrist_3_joint
  - name: /right_ur/right_ur_arm_scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_ur_arm_shoulder_pan_joint
      - right_ur_arm_shoulder_lift_joint
      - right_ur_arm_elbow_joint
      - right_ur_arm_wrist_1_joint
      - right_ur_arm_wrist_2_joint
      - right_ur_arm_wrist_3_joint
