#!/usr/bin/env bash
export HUSKY_TOP_PLATE_ENABLED=false
export HUSKY_USER_RAIL_ENABLED=false

export HUSKY_URDF_EXTRAS=$(catkin_find husky_kinova_description urdf/husky_dual_gen3_description.urdf.xacro --first-only)
