#!/usr/bin/env bash
export HUSKY_USER_RAIL_ENABLED=false
export HUSKY_LARGE_TOP_PLATE=true

export HUSKY_URDF_EXTRAS=$(catkin_find husky_kinova_description urdf/husky_gen3_robotiq_2f_85_description.urdf.xacro --first-only)
